[package]
name = "composite-pong"
version = "0.0.1"
authors = ["Guillermo Galizzi <galizzi.guillermo@gmail.com>"]

[dependencies.composite]
path = "../.."

[dependencies]
piston = "*"
piston2d-graphics = "*"
pistoncore-glutin_window = "*"
piston2d-opengl_graphics = "*"
